import type { Metadata } from "next";
import {Poppins} from 'next/font/google';
import "./globals.css";
import Header from "./components/Header";

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['400' , '600' , '700']
})

export const metadata: Metadata = {
  title: "Article",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <Header/>
        {children}
      </body>
    </html>
  );
}
